### ISSUE TITLE
Database connection problems with docker-compose

### ISSUE THREAD

**Issue by viktorstrate** [viktorstrate/photoview#10]
Multiple have reported connection issues with docker-compose

I think it is a connection problem between the api and the database (mariadb).
Please note the database version `10.4.12-MariaDB-1:10.4.12+maria~bionic`
This might be a related issue https://github.com/docker-library/mariadb/issues/262

# Replication
I have just tried to replicate the issue but everything seems to work fine. See console output below.

Can someone please try to replicate it by running
```bash
# Delete all previous volumes 
$ docker-compose down -v

# Recreate the containers from scratch
$ docker-compose up --force-recreate --build
```
When the api container prints `database migrated`, please navigate to http://localhost:8080, and you should be redirected to the initial setup wizard

<details>
  <summary>Output log</summary>

```bash
$ cp docker-compose.example.yml docker-compose.yml
$ docker-compose up
Creating network "photoview_default" with the default driver
Creating volume "photoview_db_data" with default driver
Creating volume "photoview_api_cache" with default driver
Creating photoview_db_1 ... done
Creating photoview_api_1 ... done
Creating photoview_ui_1  ... done
Creating photoview_proxy_1 ... done
Attaching to photoview_db_1, photoview_api_1, photoview_ui_1, photoview_proxy_1
api_1    | 2020/03/02 14:22:03 Connecting to database: photoview:photo-secret@tcp(db)/photoview?multiStatements=true&parseTime=true
db_1     | 2020-03-02 14:22:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.12+maria~bionic started.
db_1     | 2020-03-02 14:22:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
api_1    | 2020/03/02 14:22:03 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
db_1     | 2020-03-02 14:22:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.12+maria~bionic started.
db_1     | 2020-03-02 14:22:03+00:00 [Note] [Entrypoint]: Initializing database files
api_1    | 2020/03/02 14:22:04 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
api_1    | 2020/03/02 14:22:05 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
db_1     |
db_1     |
db_1     | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
db_1     | To do so, start the server, then issue the following commands:
db_1     |
db_1     | '/usr/bin/mysqladmin' -u root password 'new-password'
db_1     | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
db_1     |
db_1     | Alternatively you can run:
db_1     | '/usr/bin/mysql_secure_installation'
db_1     |
db_1     | which will also give you the option of removing the test
db_1     | databases and anonymous user created by default.  This is
db_1     | strongly recommended for production servers.
db_1     |
db_1     | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
db_1     | MySQL manual for more instructions.
db_1     |
db_1     | Please report any problems at http://mariadb.org/jira
db_1     |
db_1     | The latest information about MariaDB is available at http://mariadb.org/.
db_1     | You can find additional information about the MySQL part at:
db_1     | http://dev.mysql.com
db_1     | Consider joining MariaDB's strong and vibrant community:
db_1     | https://mariadb.org/get-involved/
db_1     |
db_1     | 2020-03-02 14:22:06+00:00 [Note] [Entrypoint]: Database files initialized
db_1     | 2020-03-02 14:22:06+00:00 [Note] [Entrypoint]: Starting temporary server
db_1     | 2020-03-02 14:22:06+00:00 [Note] [Entrypoint]: Waiting for server startup
db_1     | 2020-03-02 14:22:06 0 [Note] mysqld (mysqld 10.4.12-MariaDB-1:10.4.12+maria~bionic) starting as process 122 ...
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Using Linux native AIO
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Uses event mutexes
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Number of pools: 1
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Using SSE2 crc32 instructions
db_1     | 2020-03-02 14:22:06 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Completed initialization of buffer pool
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Waiting for purge to start
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: 10.4.12 started; log sequence number 60972; transaction id 21
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1     | 2020-03-02 14:22:06 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1     | 2020-03-02 14:22:06 0 [Warning] 'user' entry 'root@0829d713736a' ignored in --skip-name-resolve mode.
db_1     | 2020-03-02 14:22:06 0 [Warning] 'user' entry '@0829d713736a' ignored in --skip-name-resolve mode.
db_1     | 2020-03-02 14:22:06 0 [Warning] 'proxies_priv' entry '@% root@0829d713736a' ignored in --skip-name-resolve mode.
db_1     | 2020-03-02 14:22:06 0 [Note] InnoDB: Buffer pool(s) load completed at 200302 14:22:06
db_1     | 2020-03-02 14:22:06 0 [Note] Reading of all Master_info entries succeeded
db_1     | 2020-03-02 14:22:06 0 [Note] Added new Master_info '' to hash table
db_1     | 2020-03-02 14:22:06 0 [Note] mysqld: ready for connections.
db_1     | Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
api_1    | 2020/03/02 14:22:06 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
db_1     | 2020-03-02 14:22:07+00:00 [Note] [Entrypoint]: Temporary server started.
api_1    | 2020/03/02 14:22:07 ERROR: Could not ping database, exiting
db_1     | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
api_1    | 2020/03/02 14:22:08 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
api_1    | 2020/03/02 14:22:09 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
api_1    | 2020/03/02 14:22:10 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
api_1    | 2020/03/02 14:22:11 ERROR: Could not ping database, exiting
photoview_api_1 exited with code 1
db_1     | 2020-03-02 14:22:13+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: jeixeiM8Ahjee4phiathai7beith8boh
db_1     | 2020-03-02 14:22:13 10 [Warning] 'proxies_priv' entry '@% root@0829d713736a' ignored in --skip-name-resolve mode.
db_1     | 2020-03-02 14:22:13+00:00 [Note] [Entrypoint]: Creating database photoview
db_1     | 2020-03-02 14:22:13+00:00 [Note] [Entrypoint]: Creating user photoview
db_1     | 2020-03-02 14:22:13+00:00 [Note] [Entrypoint]: Giving user photoview access to schema photoview
db_1     | 2020-03-02 14:22:13 14 [Warning] 'proxies_priv' entry '@% root@0829d713736a' ignored in --skip-name-resolve mode.
db_1     |
db_1     | 2020-03-02 14:22:13+00:00 [Note] [Entrypoint]: Stopping temporary server
db_1     | 2020-03-02 14:22:13 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
db_1     | 2020-03-02 14:22:13 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1     | 2020-03-02 14:22:13 0 [Note] InnoDB: FTS optimize thread exiting.
db_1     | 2020-03-02 14:22:13 0 [Note] InnoDB: Starting shutdown...
db_1     | 2020-03-02 14:22:13 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1     | 2020-03-02 14:22:13 0 [Note] InnoDB: Buffer pool(s) dump completed at 200302 14:22:13
api_1    | 2020/03/02 14:22:13 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Shutdown completed; log sequence number 60981; transaction id 24
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1     | 2020-03-02 14:22:14 0 [Note] mysqld: Shutdown complete
db_1     |
db_1     | 2020-03-02 14:22:14+00:00 [Note] [Entrypoint]: Temporary server stopped
db_1     |
db_1     | 2020-03-02 14:22:14+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
db_1     |
db_1     | 2020-03-02 14:22:14 0 [Note] mysqld (mysqld 10.4.12-MariaDB-1:10.4.12+maria~bionic) starting as process 1 ...
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Using Linux native AIO
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Uses event mutexes
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Number of pools: 1
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Using SSE2 crc32 instructions
db_1     | 2020-03-02 14:22:14 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Completed initialization of buffer pool
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Waiting for purge to start
api_1    | 2020/03/02 14:22:14 Could not ping database: dial tcp 172.19.0.2:3306: connect: connection refused. Will retry after 1 second
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: 10.4.12 started; log sequence number 60981; transaction id 21
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1     | 2020-03-02 14:22:14 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1     | 2020-03-02 14:22:14 0 [Note] Server socket created on IP: '::'.
db_1     | 2020-03-02 14:22:14 0 [Warning] 'proxies_priv' entry '@% root@0829d713736a' ignored in --skip-name-resolve mode.
db_1     | 2020-03-02 14:22:14 0 [Note] InnoDB: Buffer pool(s) load completed at 200302 14:22:14
db_1     | 2020-03-02 14:22:14 0 [Note] Reading of all Master_info entries succeeded
db_1     | 2020-03-02 14:22:14 0 [Note] Added new Master_info '' to hash table
db_1     | 2020-03-02 14:22:14 0 [Note] mysqld: ready for connections.
db_1     | Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
api_1    | 2020/03/02 14:22:15 Database migrated
api_1    | 2020/03/02 14:22:15 🚀 Graphql playground ready at http://localhost:8080/api
```

</details>

**Comment by Nobrac** [comment]
I rebuild it but I still can't create the initial user.

[outputlog.txt](https://github.com/viktorstrate/photoview/files/4277481/outputlog.txt)

**Comment by viktorstrate** [comment]
@Nobrac thank you for the logs, it looks like the api connects successfully to the database after some attempts. 🤔

Do you receieve any errors or warnings in the javascript console (F12 -> Console).
If you navigate to the networks tab, can you then see any "Fetch" requests, or anything unusual?

I've attach a screenshot of what it is supposed to look like:

<img width="1680" alt="Screenshot 2020-03-02 at 20 32 05" src="https://user-images.githubusercontent.com/4233458/75710464-e72c3180-5cc4-11ea-85b0-0ad0d31227a6.png">

**Comment by Nobrac** [comment]
@viktorstrate I'm not sure if there is anything unusual. I'm a completely beginner in web development. I'm sorry for that.

I attach you the screenshot.

![Network](https://user-images.githubusercontent.com/22682116/75711505-d086da00-5cc6-11ea-8278-e3fdccc0f9ec.JPG)

**Comment by viktorstrate** [comment]
No problem at all :)
It might be a CORS problem.

Do you get any errors in the console?
Did you write http://localhost:8080 in the address bar to access the server, or an ip?

**Comment by Nobrac** [comment]
I try it with the IP of the virtual machine. The console gives me several errors that Firefox can't connect to ws://localhost:8080/api

So maybe that's already the problem? 

Do I need to install Linux with a GUI so I can use http://localhost:8080 in the local browser on the machine or is there a way I can tell the machine it should listen on 192.168.178.75:8080 for example?

![Console](https://user-images.githubusercontent.com/22682116/75712416-2e67f180-5cc8-11ea-8e6d-22e525c33ad8.JPG)

**Comment by Nobrac** [comment]
Ah I think I got the fix. I changed "localhost" with the local IP of my virtual machine in the docker-compose.yml file. After that I rebuild everything with 
`
# Delete all previous volumes 
$ docker-compose down -v

# Recreate the containers from scratch
$ docker-compose up --force-recreate --build`

And now I got the setup screen.

![setup](https://user-images.githubusercontent.com/22682116/75713037-5146d580-5cc9-11ea-801d-5b26e2e4d618.JPG)

**Comment by viktorstrate** [comment]
Awesome, thank you for helping out 🎉

For security reasons, the server will currently only allow the ip or domain specified in the docker-compose file to connect. The documentation should probably be clearer

This process of setting it up will hopefully also be improved with #9

**Comment by Nobrac** [comment]
Thank you too for your help. :)

And thank you for such a nice project!

**Comment by viktorstrate** [comment]
Thanks again, if you find any new problems feel free to open a new issue.

For now I will let this issue stay open, until the documentation has been cleared up.

**Comment by ChiefMedicalOfficer** [comment]
> Ah I think I got the fix. I changed "localhost" with the local IP of my virtual machine in the docker-compose.yml file. After that I rebuild everything with the commands you mentioned in your first post:
> # Delete all previous volumes
> 
> $ docker-compose down -v
> # Recreate the containers from scratch
> 
> $ docker-compose up --force-recreate --build
> 
> And now I got the setup screen.
> 
> ![setup](https://user-images.githubusercontent.com/22682116/75713037-5146d580-5cc9-11ea-801d-5b26e2e4d618.JPG)

This fixed it. Nice work.

**Comment by jeroenpardon** [comment]
@viktorstrate sorry for taking so long to get back to you. When I reported to you on reddit I had already used my local IP instead of localhost (and tried on my domain as well). 

Attempts to remedy the issues with the instructions here didn't work initially. Today I tried the same on a different machine. And after quite a bit of failed pings to the database it started working and I got to the initial setup screen.

I was using the same docker compose file as before on the first server (well, changed the IP adress obviously). Very weird.

I am going to test on the first machine again (as that is the one I want to be running the app on) and see if I can find out what is making the difference.

**Comment by viktorstrate** [comment]
The last couple of times I have built the container from scratch this problem didn't occur.
I'm closing the issue, if anyone experiences a problem like this again, feel free to open a new issue.

**Comment by brink668** [comment]
I am having this issue on Docker with 2.1.1.  I am running it within a Synology Nas 920+

`

021-02-24 13:37:24 | stdout |  
-- | -- | --
2021-02-24 13:37:24 | stdout | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c74b6]
2021-02-24 13:37:24 | stdout | panic: runtime error: invalid memory address or nil pointer dereference
2021-02-24 13:37:19 | stdout | 2021/02/24 13:37:19 WARN: Could not ping database: dial tcp: lookup db on 192.168.0.6:53: no such host. Will retry after 5 seconds
2021-02-24 13:37:19 | stdout | [0m[31m[error] [0mfailed to initialize database, got error dial tcp: lookup db on 192.168.0.6:53: no such host
2021-02-24 13:37:19 | stdout | 2021/02/24 13:37:19 [35m/app/database/database.go:105
2021-02-24 13:37:19 | stdout |  
2021-02-24 13:37:19 | stdout | 2021/02/24 13:37:19 Connecting to MYSQL database: photoview:photosecret@tcp(db)/photoview?multiStatements=true&parseTime=true
2021-02-24 13:37:14 | stdout | 2021/02/24 13:37:14 WARN: Could not ping database: dial tcp: lookup db on 192.168.0.6:53: no such host. Will retry after 5 seconds
2021-02-24 13:37:14 | stdout | [0m[31m[error] [0mfailed to initialize database, got error dial tcp: lookup db on 192.168.0.6:53: no such host
2021-02-24 13:37:14 | stdout | 2021/02/24 13:37:14 [35m/app/database/database.go:105
2021-02-24 13:37:14 | stdout |  
2021-02-24 13:37:14 | stdout | 2021/02/24 13:37:14 Connecting to MYSQL database: photoview:photosecret@tcp(db)/photoview?multiStatements=true&parseTime=true
2021-02-24 13:37:09 | stdout | 2021/02/24 13:37:09 WARN: Could not ping database: dial tcp: lookup db on 192.168.0.6:53: no such host. Will retry after 5 seconds
2021-02-24 13:37:09 | stdout | [0m[31m[error] [0mfailed to initialize database, got error dial tcp: lookup db on 192.168.0.6:53: no such host
2021-02-24 13:37:09 | stdout | 2021/02/24 13:37:09 [35m/app/database/database.go:105
2021-02-24 13:37:09 | stdout |  
2021-02-24 13:37:09 | stdout | 2021/02/24 13:37:09 Connecting to MYSQL database: photoview:photosecret@tcp(db)/photoview?multiStatements=true&parseTime=true
2021-02-24 13:37:04 | stdout | 2021/02/24 13:37:04 WARN: Could not ping database: dial tcp: lookup db on 192.168.0.6:53: no such host. Will retry after 5 seconds
2021-02-24 13:37:04 | stdout | [0m[31m[error] [0mfailed to initialize database, got error dial tcp: lookup db on 192.168.0.6:53: no such host
2021-02-24 13:37:04 | stdout | 2021/02/24 13:37:04 [35m/app/database/database.go:105
2021-02-24 13:37:04 | stdout |  
2021-02-24 13:37:04 | stdout | 2021/02/24 13:37:04 Connecting to MYSQL database: photoview:photosecret@tcp(db)/photoview?multiStatements=true&parseTime=true
2021-02-24 13:36:59 | stdout | 2021/02/24 13:36:59 WARN: Could not ping database: dial tcp: lookup db on 192.168.0.6:53: no such host. Will retry after 5 seconds
2021-02-24 13:36:59 | stdout | [0m[31m[error] [0mfailed to initialize database, got error dial tcp: lookup db on 192.168.0.6:53: no such host
2021-02-24 13:36:59 | stdout | 2021/02/24 13:36:59 [35m/app/database/database.go:105
2021-02-24 13:36:59 | stdout |  
2021-02-24 13:36:59 | stdout | 2021/02/24 13:36:59 Connecting to MYSQL database: photoview:photosecret@tcp(db)/photoview?multiStatements=true&parseTime=true
2021-02-24 13:36:59 | stdout | 2021/02/24 13:36:59 No .env file found

`

**Comment by viktorstrate** [comment]
@brink668 make sure your connection to the database is right. If this is related to the Synology try to ask on the Discord server, there might be someone who knows more about that.

**Comment by brink668** [comment]
Okay will do.  Just a quick question then.  Do i need to supply my only database or is that part of the Docker Container?

**Comment by viktorstrate** [comment]
If you use the docker-container configuration it is.

**Comment by ultranol** [comment]
I am at my wits end with this issue. Nothing works. Database in a container, database in the host where the containers run on, I can't for the life of me get it to show the initial setup screen. The logs show the database connecting fine, both when I have one running on the host, and when it uses the "photoview_db_1" container. If the DB is empty, it shows the main container creating the "users" table there and everything. How come not getting the initial setup screen is a connection issue from the main container to the database if the logs show the connection is working fine?
