### ISSUE TITLE
No Initial Setup screen on first build

### ISSUE THREAD

**Issue by MackWells115** [viktorstrate/photoview#11]
I did a docker-compose installation following the steps on the ReadME file. Docker-compose builds everything fine, but the first screen is a normal login screen instead of a setup screen, so I have no way of logging in since I never did the setup for it. Any way to add an admin account or rebuild it in a way that will show the setup screen?

**Comment by viktorstrate** [comment]
The is likely a problem with the connection between the front-end and the back-end.
Multiple others have had simmilar problems, where the solution was to change localhost in the docker-compose to the ip where the server is accessed from.

Please see issue #10 for more information.

**Comment by MackWells115** [comment]
Thank you yes it's because I forgot to change the port for the environment variable in docker-compose.yml to the port I changed the rest of the build too. Thank you so much!
