### ISSUE TITLE
Setup for a domain hosted at a hosting provider

### ISSUE THREAD

**Issue by costincca** [viktorstrate/photoview#111]
Hello. Great gallery (good looking, responsive). I would like to host it where my domain is, on a third party server, for which I have FTP access, Softacoulous, not much more. I can run php, have mysql DBs, though.

Is there any chance to have a setup for this kind of installation? Or port the code somehow?

**Comment by viktorstrate** [comment]
Hi @costincca, check if your hosting provider supports Docker.
