### ISSUE TITLE
Pictures should be shown in ascending (old to new)

### ISSUE THREAD

**Issue by abunasar** [viktorstrate/photoview#120]
Hello,

It would be great if you could add an option to display images in an album in either ascending or descending order. For example there's an album called: New York trip - 2020, you go to the album and all the latest pictures are on top and older ones are at bottom, should be the other way around I believe.

thanks

**Comment by viktorstrate** [comment]
Hi @abunasar

This is actually already been implemented in pull-request #99,
but a new release hasn't been pushed yet. I will push the next release soon though.

If you click the Watch button, the select Releases Only, you will be notified when it goes live.

**Comment by abunasar** [comment]
> Hi @abunasar
> 
> This is actually already been implemented in pull-request #99,
> but a new release hasn't been pushed yet. I will push the next release soon though.
> 
> If you click the Watch button, the select Releases Only, you will be notified when it goes live.

Thank you!
