### ISSUE TITLE
Visitor IPs behind cloudflare

### ISSUE THREAD

**Issue by abunasar** [viktorstrate/photoview#126]
Hello,

It would be great if you could add an option to get visitors real ips if the gallery is behind cloudflare by adding the setting in  admin panel where we could add list of cloudflare ips and CF-Connecting-IP/X-Forwarded-For prefixes.
https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs-Logging-visitor-IP-addresses

thanks

**Comment by viktorstrate** [comment]
Hi @abunasar,
I'm sorry if i'm asking a trivial question, but I don't know much about CloudFlare proxies.
But what is this needed for, Photoview currently doesn't currently log the IP of the visitors.

**Comment by viktorstrate** [comment]
I will close this, if someone can elaborate what is needed and why, I'll reopen it.
