### ISSUE TITLE
Mobile phone upload

### ISSUE THREAD

**Issue by nebulade** [viktorstrate/photoview#129]
Hi, this looks awesome. I wanted to ask if there are any plans to provide some way to have automatic upload from mobile phones? In my case that would be Android.

**Comment by viktorstrate** [comment]
Hi thank you.

Photoview doesn’t touch your photos and I think that is one of its strengths, though it is certainly also a weakness.

I think the best option would be to use an app to upload the photo via a file server like FTP, the let Photoview automatically detect the new files.

After a quick google search, I found this
https://play.google.com/store/apps/details?id=com.touchbyte.photosync&hl=en_US&gl=US
