### ISSUE TITLE
Don't scan hidden folders

### ISSUE THREAD

**Issue by jeroenpardon** [viktorstrate/photoview#13]
When hidden folders contain images, they are scanned and put into an album.

In my case a .sync folder was created at the root of my photos directory by resilio sync. I know other syncing and file management applications (like filerun for example) use hidden folders as a cache for browsing pictures. 

I think Photoview should ignore hidden folders and files, or have an option to do so.

**Comment by viktorstrate** [comment]
This should be resolved in the latest commit.
You can update by running

```sh
$ git pull
$ docker-compose build
$ docker-compose down && docker-compose up -d
```

After rescanning, the hidden albums should be removed
