### ISSUE TITLE
Invalid Authorisation Token

### ISSUE THREAD

**Issue by eldudemeister** [viktorstrate/photoview#134]
Hi, I've been using this but had to delete and recreate the containers a couple of times and now I have an error saying invalid authorisation token? There doesnt appear to be anything in the logs and my docker compose is below?
``` photoviewdb:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photo_view
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photo-secret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

 photoview:
    image: viktorstrate/photoview:1
    restart: always
    ports:
      - "8282:80"
    environment:
      - MYSQL_URL=photoview:photo-secret@tcp(photoviewdb)/photoview
      - API_LISTEN_IP=photoview
      - API_LISTEN_PORT=80
      - PHOTO_CACHE=/app/cache
      - PUBLIC_ENDPOINT=http://unraidserv.local:8282/
      - MAPBOX_TOKEN=XXXX
    volumes:
      - api_cache:/app/cache
      - /mnt/user/photos/Pictures:/photos:ro
volumes:
  db_data:
  api_cache:
```
Could I have some help or pointers please?

**Comment by viktorstrate** [comment]
This could be because your browser has cached an old version. Try to delete the browser cache for the site.

In the browser, click on the padlock right before the url, then:
- Firefox: click `Clear site data`
- Chrome: click `Site info` -> `Clear data`

**Comment by eldudemeister** [comment]
Thanks, deleting the browser cache didn’t work for some reason but if I open up a private browser window I can get access again. Is there anything else I can try?

**Comment by viktorstrate** [comment]
Make sure you delete cookies as well

**Comment by viktorstrate** [comment]
Let this issue stay open, if a token becomes invalid, it should automatically be removed.

**Comment by eldudemeister** [comment]
That was it, thanks!

**Comment by viktorstrate** [comment]
Hmm, I can't seem to replicate it. When I set an invalid access token, it does just automatically remove it as expected.
It might have been because of some incompatibility after a version update.
