### ISSUE TITLE
Doesn't work correctly via macOS Safari

### ISSUE THREAD

**Issue by narensankar0529** [viktorstrate/photoview#146]
Server is on a Synology via NAS.
Can connect via Safari - but when switching to the settings screen it shows just a blank screen. 

Works correctly using MSFT Edge on the same machine.

**Comment by viktorstrate** [comment]
Hmm, it works just fine for me with Safari on my macbook pro.
Does it work in a private window?

**Comment by narensankar0529** [comment]
I tried on a private window and it fails as well. Safari build is Version 14.0.1 (15610.2.11.51.10, 15610)

**Comment by viktorstrate** [comment]
Okay, do you get any errors in the console?

A guide on opening the console on Safari
https://balsamiq.com/support/faqs/browserconsole/#apple-safari

**Comment by narensankar0529** [comment]
[Log] GRAPHQL ENDPOINT – "http://192.168.1.220:10007/api/graphql" (src.0fa31d5c.js, line 1863)
[Error] WebSocket connection to 'ws://192.168.1.220:10007/api/graphql' failed: Unexpected response code: 403
[Error] TypeError: undefined is not an object (evaluating 'e.siteInfo') — SettingsPage.33c9d628.js:2:4237
	Lu (src.0fa31d5c.js:15:82878)
	(anonymous function) (src.0fa31d5c.js:15:84993)
	Oa (src.0fa31d5c.js:15:49055)
	Iu (src.0fa31d5c.js:15:86729)
	es (src.0fa31d5c.js:15:103020)
	es
	(anonymous function) (src.0fa31d5c.js:11:3934)
	Ji (src.0fa31d5c.js:15:99759)
	Vi (src.0fa31d5c.js:15:95751)
	Vi
	(anonymous function) (src.0fa31d5c.js:15:45563)
	(anonymous function) (src.0fa31d5c.js:11:3934)
	ha (src.0fa31d5c.js:15:45510)
	pa (src.0fa31d5c.js:15:45445)
	as (src.0fa31d5c.js:15:104778)
	(anonymous function) (src.0fa31d5c.js:11:3934)
	(anonymous function) (src.0fa31d5c.js:15:103971)
	R (src.0fa31d5c.js:11:2904)
	(anonymous function) (src.0fa31d5c.js:11:1617)
[Error] TypeError: undefined is not an object (evaluating 'e.siteInfo')
	(anonymous function) (src.0fa31d5c.js:11:1694)

**Comment by helmut72** [comment]
Same problem on my Mac and iPad. Settings doesn't open.

**Comment by viktorstrate** [comment]
This has been fixed by 4980a77
