### ISSUE TITLE
Allow hosting under subpath

### ISSUE THREAD

**Issue by simhnna** [viktorstrate/photoview#20]
I tried to host photoview under a subpath `localhost/photos` but couldn't get it to work. All the js/css resources are being loaded from `/`

Would be nice if photoview supported running under a subpath, since that would make hosting it in internal networks easy

**Comment by viktorstrate** [comment]
Thank you for opening the issue.

I'm currently in the working of rewriting the docker setup. I will work on a way to specify this from the docker-compose.yml file.

What is your setup, if I may ask, are you using a reverse proxy to redirect traffic from the sub path to photoview?

**Comment by simhnna** [comment]
yes I'm using nginx as a reverse proxy and proxying /photos to photoview

**Comment by viktorstrate** [comment]
Okay thank you, I've come a long way with the docker rewrite today.
I will test and make sure subpaths can be configured from docker-compose.yml after the rewrite.

**Comment by viktorstrate** [comment]
I have just pushed the new docker rewrite. I will be working on this next
