### ISSUE TITLE
Comparison with Lychee

### ISSUE THREAD

**Issue by A1CY0N** [viktorstrate/photoview#21]
I'm pleased to discover this cool application that corresponds to what I've been looking for since a long time. It seems that you didn't include lychee (https://lychee.electerious.com/) in the list of available alternatives. What is the advantage of photoview compared to Lychee ?

**Comment by viktorstrate** [comment]
Lychee is a great alternative, and it should probably be mentioned in the Readme as well.

I have only used Lychee for small testing, so I don't know how it differs from Photoview.
Lychee supports plugins and with `lycheesync` I think it can do more or less the same as Photoview currently can do.

As far as I can see Lychee doesn't support RAW photos, which (for me) is quite an important feature.

Another difference between them is complexity. While Lychee is more advanced and can do much more than Photoview. It is also more complex to setup and manage.
