### ISSUE TITLE
Scan error on column index 0, name "orientation": converting NULL to int is unsupported

### ISSUE THREAD

**Issue by SlavikCA** [viktorstrate/photoview#29]
I added few photos and started "Scan".

For most of the photos, I'm getting same scan error:

2020/04/14 20:11:34 Scanning for EXIF
2020/04/14 20:11:34 WARN: Could not read LensModel from EXIF: IMG_6433.JPG
2020/04/14 20:11:34 WARN: Could not read Orientation from EXIF: IMG_6433.JPG
2020/04/14 20:11:34 WARN: Could not read ExposureProgram from EXIF: IMG_6433.JPG
2020/04/14 20:11:34 Broadcasting notification: Scan completed
2020/04/14 20:11:34 Broadcasting notification: Processing photos (0 of 137)
2020/04/14 20:11:34 Processing photo: /photos/2010 11 Thanksgiving - SNOW/IMG_1438.JPG
2020/04/14 20:11:34 ERROR: Could not process photo (/photos/2010 11 Thanksgiving - SNOW/IMG_1438.JPG): sql: Scan error on column index 0, name "orientation": converting NULL to int is unsupported
2020/04/14 20:11:34 Broadcasting notification: Scanner error

Any workaround for this issue?

**Comment by SlavikCA** [comment]
[IMG_1438.zip](https://github.com/viktorstrate/photoview/files/4478286/IMG_1438.zip)

**Comment by viktorstrate** [comment]
Thank you for reporting the bug and providing an image 👍
