### ISSUE TITLE
UI issues: "View all photos of the album"

### ISSUE THREAD

**Issue by SlavikCA** [viktorstrate/photoview#36]
I really like the general UI of the photoview.
That's what's special about this product. I think no other apps can show such a nice and fast overview.

However, there are few workflows which supported rather poorly.
Specifically, this workflow: "View all photos of the album"

**A**. I'm using mouse (or touch screen) to navigate to the album.
**B**. I'm opening 1st photo fullsize (fullscreen)
**C**. Now, there is no way to proceed to the next photo with the mouse (or touch screen). Also, you can't close full view using a mouse or touchscreen.
- On the desktop computer I have to use the keyboard (and click => or <= ), which is inconvenient. 
- But on the mobile device, you really are stuck, because there is no keyboard. 
And since the BACK button doesn't work, too (see #35) - it is really an issue.

Suggestion:
- add PREV and NEXT action by mouse click (or tap/slide) on the left or right side of the image.
- I'm not sure, how to handle ESC case (closing fullview without keyboard). May be "X" icon at the top corner? or something else?

**Comment by viktorstrate** [comment]
This area of the web UI simply needs more work, thanks for opening the issue though.
This is also somewhat related to #7
