### ISSUE TITLE
Ignore hidden files

### ISSUE THREAD

**Issue by viktorstrate** [viktorstrate/photoview#57]
The scanner already ignores hidden directories and hidden files are often just metadata.

**Comment by stz184** [comment]
By hidden files do you mean the dotfiles or such as hidden attribute set (like in NTFS)?

**Comment by viktorstrate** [comment]
I was thinking about dotfiles, I have never tested Photoview on Windows.
This should be an easy fix, but I've often gotten error notifications because of misread hidden metadata files.
