### ISSUE TITLE
Favourite images

### ISSUE THREAD

**Issue by viktorstrate** [viktorstrate/photoview#6]
- [x] When the heart icon on a photo is clicked, the image should be favourited so it is easier to find.
- [ ] There should be a way to filter favourited photos. Maybe a link in the sidebar?

**Comment by stz184** [comment]
I am on it :)

**Comment by stz184** [comment]
Just a quick update: excuse me for the delay, but I had a really busy time at work. I have started working on this issue yesterday. The backend is ready, I am now working on the frontend part. Bear with me!

**Comment by stz184** [comment]
I have a few questions about the presentation of the favorites:
1) Should we display all favorites from all albums all together or grouped by album they belong to (like the /photos view)?
2) If we go with the second approach, what album title link should be? It may lead you to the corresponding album page showing all items in this particular album or only the favorites in it?
3) Do you think it is a good idea when you are on /favorites page and unfav some items to update the view, removing the items?

**Comment by viktorstrate** [comment]
No worries there's no rush, I really appreciate your help :)

My idea of how all this should work is not _set in stone_ at all yet, but here is some of my thoughts.

> 1. Should we display all favorites from all albums all together or grouped by album they belong to (like the /photos view)?

I think grouping them by album would make the most sense, this would make it easy to browse all favorited images in one place, but still with some structure.

> 2. [...] what album title link should be? It may lead you to the corresponding album page showing all items in this particular album or only the favorites in it?

I think linking to the full album would be fine (and the simplest), especially if the favorites page shows all favorited images for each album already.

> 3. Do you think it is a good idea when you are on /favorites page and unfav some items to update the view, removing the items?

I think they should be there until you refresh the page or navigate away and back again, so users can undo if it was a mistake.

----

I also think it could be nice to have the option to filter only favorited images when viewing a single album.
Maybe a checkbox right below the album title to `Show only favorites`.
There could also be an option for sorting preferences (like `date`, `filename`, `filetype`) next to it, but that could be a for another pull-request ;)
(What are your thoughts on all that?)

**Comment by stz184** [comment]
Hi, @viktorstrate !
Thanks for the answers. These are my comments:
- Grouping by album is nice indeed, but showing all the favorited images on the same page is not. What if the user has too many favorites from a single album? I have to provide some limit to the query, I can't just assume that the favorites would not be too much. I suggest to show the favorites grouped by album, with the same limit as /photos page, but when you click on the album title to go page like `/album/19/favorites` where all favorites from the corresponding album are shown.
- About the checkbox - I will add one, I like the idea
- About the sorting options - I also like the idea, can you please add a separate issue and "assign" it to me? Thanks!

**Comment by viktorstrate** [comment]
> Grouping by album is nice indeed, but showing all the favorited images on the same page is not.

That's a good point, but limiting max shown favorited images per album also only solves the problem partially.
What if the user has many albums with favorited photos, the page would also be very slow.

This is already a bigger problem on the `/photos` page, if the user has a lot of directories.
I hope to improve this with the implementation of the timeline view #48.

Perhaps we could find a better solution for the `/favorites` page?
One idea could be to not have a `/favorites` page directly, but instead have the same checkbox on the `/photos` page as on the individual `/album` pages. When checked all non-favorited images would be hidden, and the page would be nearly identical to a dedicated `/favorites` page. Aside from a simpler, more consistent user-interface, the code would also be simpler, as a `/favorites` page could be omitted entirely.
I really want to hear what you think about that idea?

> About the sorting options - I also like the idea, can you please add a separate issue and "assign" it to me? Thanks!

I'll open a new issue for the sorting options, great you wanna take that as well!

**Comment by stz184** [comment]
You are right, my suggestion resolves the problem just partially. 
What if the photos pages have infinite scroll instead of loading all the albums from the beginning? 

I think that separate /favorites pages will be nice if /photos page is changed to timeline style as #48 suggests. If it remains as is in the moment, it does not really make sense to have separate /favorites page - a hearth icon next to the share button right of the title will be enough. 

What do you think?

p.s. I just realized that separate URL /favorites or /photos/favorites will make it possible to share a link directly to the favorites.
We can have the same for albums - /album/foo-bar/favorites may show only the favorites from a particular album.

**Comment by stz184** [comment]
Ok, I will just add a filtering button then :)

**Comment by stz184** [comment]
I just sent a PR https://github.com/viktorstrate/photoview/pull/75
Please take a look when you have some time and don't hesitate to ask me anything. 

Regards!
