### ISSUE TITLE
Show photos by location on a map

### ISSUE THREAD

**Issue by viktorstrate** [viktorstrate/photoview#68]
Add "Places" to the sidebar, which when clicked will show a map with all geo-tagged photos.
Inspired by the Photos app by Apple.

<img src="https://help.apple.com/assets/5D7C3C6C680CE20A4EEF0365/5D7C3C7F680CE20A4EEF036C/en_US/f8ee4e14a8b63880d96c6f12977013d5.png" width="300" />

Mapbox could be used with its [clusters feature](https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/), to render the photos onto the map.

**Comment by arnaubennassar** [comment]
I'd love to see this implemented
