### ISSUE TITLE
Show image metadata

### ISSUE THREAD

**Issue by arnaubennassar** [viktorstrate/photoview#74]
Right now when clicking on an image, a left panel appears. It would be great to display some metadata there, like:
- date
- location
- file name
- info of the camera that took the photo

**Comment by viktorstrate** [comment]
Hi @arnaubennassar 
This metadata is already being shown for photos with EXIF data.
On the demo site, only some of the photos have attached exif data, take a look at the RAW files in the 'Some RAW images' album.

<img width="412" alt="Screenshot 2020-09-06 at 18 48 00" src="https://user-images.githubusercontent.com/4233458/92330732-80bc0d80-f071-11ea-891c-84e22f5c26c7.png">

I am closing this issue, if this is not what you ment, please reply and I will reopen it.

**Comment by arnaubennassar** [comment]
I don't know how photo metadata works.
With that being said, I'm comparing PiGallery2 and Photoview (with same photo library), and PiGallery is able to provide more info on the images. 

I guess that there are other metadata apart from EXIF, that could be used to show info.

**Comment by viktorstrate** [comment]
Ah okay. Could you provide a sample image as well as a screenshot of the information in PiGallery2?

You can send the image privately to me if you don't have a photo you want to share publicly, otherwise just zip it attach it to a comment.

**Comment by arnaubennassar** [comment]
My bad, I did a bad comparision :S
