### ISSUE TITLE
Photo duplication detection

### ISSUE THREAD

**Issue by viktorstrate** [viktorstrate/photoview#8]
Some cameras can be set to save both raw and jpeg photos.

Detect duplicate photos with different types but identical names.
And only show one photo in the UI but let users be able to download all versions, from the side menu.

**Comment by ConfuSomu** [comment]
This could be extended to support videos and photos that have the same filename. For example, Live Photos on iOS devices when exported are composed of two files a jpeg/heic (depends on setting) and a mov file.

A button would have to be added when viewing the photo to play the video file.
